
service: aws-serverless-nodejs-datadog-otel

plugins:
  - serverless-pseudo-parameters
  - serverless-plugin-datadog

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

  tracing: true
  iamRoleStatements:
    - Effect: Allow # xray permissions (required)
      Action:
        - xray:PutTraceSegments
        - xray:PutTelemetryRecords
      Resource:
        - "*"


custom:
  datadog:
    flushMetricsToLogs: true
    apiKey: ${ssm:/service/demo-lambda-datadog/datadog/apikey}
    addLayers: true
    logLevel: "info"
    enableXrayTracing: true
    enableDDTracing: true
    forwarderArn: arn:aws:lambda:us-east-1:864945005820:function:datadog-forwarder-Forwarder-9HL2PKKMPC7F
    enableTags: true
    injectLogContext: true
    exclude: 
      - dd-excluded-function

functions:
  hello:
    handler: handler.hello
